### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by hecperleo** [adityag6994/3D_Object_Seg_CNN#1]
Hi, you have missed at line 128 `std::`

`std::ofstream myfile;`

Fixing that your code compiles fine. I saw on YouTube that you will make a tutorial, sorry for asking here I know that is not right place to do it. It is possible to use your .cpp to detect objects just using a `PointCloud2` topic? I am using a velodyne to provide me a point cloud 2 on `/velodyne_points` and I want to detect different objects and distance to them. 

Thank you.

**Comment by adityag6994** [comment]
Hey thanks for the correction. So although I am getting data in XYZRGB format from camera, I am only using XYZ in the tracker. Which means, and according to this (http://pointclouds.org/documentation/tutorials/hdl_grabber.php) velodyne gives it in the form XYZI, so I think it should work.If you let tracker only use XYZ out of XYZI. Please let me know if it works. 

PS: Procrastination is taking place, thanks for reminding, I’ll work on the blog :)
